---
language: node_js
node_js:
  - "lts/*"

sudo: false
dist: xenial

cache:
  directories:
    - node_modules
    - apps/contribution/node_modules
    - apps/contributor/node_modules
    - apps/proposal/node_modules
    - apps/token/node_modules
    - apps/vault/node_modules

install:
  - npm install -g @aragon/cli
  - npm install -g truffle
  - npm install

before_script:
  - npm run devchain &
  - ipfs daemon --offline &

script:
  - npm run lint:wrapper
  - npm run lint:contract-tests
  - npm run test
  - npm run bootstrap

branches:
  only:
    - master
