---
language: node_js
node_js:
  - "11"

sudo: false
dist: xenial

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:wrapper
  - yarn lint:contracts

branches:
  only:
    - master
