---
language: node_js
node_js:
  - "lts/*"

sudo: false
dist: xenial

cache:
  directories:
    - node_modules
    - apps/contribution/node_modules
    - apps/contributor/node_modules
    - apps/proposal/node_modules
    - apps/token/node_modules
    - apps/vault/node_modules

env:
  - TASK=lint:wrapper
  - TASK=lint:contract-tests
  - TASK=test:token
  - TASK=test:contributor
  - TASK=test:contribution
  - TASK=test:proposal

install:
  - npm install -g @aragon/cli
  - npm install -g truffle
  - npm install

before_script:
  - npm run devchain > /dev/null &
  - sleep 5

script:
  - travis_wait 60 npm run $TASK

branches:
  only:
    - master