---
language: node_js
node_js:
  - "lts/*"

sudo: false
dist: xenial

install:
  - npm install
  - npm run install-all

script:
  - npm run lint:wrapper
  - npm run lint:contract-tests
  - npm run devchain & travis_wait 60 npm test

branches:
  only:
    - master
